src/utils/__tests__/azure_storage.test.ts
src/utils/azure_storage.ts

Needed to pass the leaseId to lock the Blob.

Allow options in getBlob* functions

---

.gitignore
openapi/definitions.yaml
src/models/service.ts

This PR aims to extend the `Service` model  by adding the metadata defined in [io-services-metadata](https://github.com/teamdigitale/io-services-metadata/blob/master/definitions.yml#L6).

[#170127598] extended service model

---

openapi/definitions.yaml
src/models/visible_service.ts

This PR aims to extend the `VisibleService` model by adding the metadata defined in [io-services-metadata](https://github.com/teamdigitale/io-services-metadata/blob/master/definitions.yml#L6).

[#170127598] Add ServiceMetadata to VisibleService model

---

src/utils/middlewares/azure_api_auth.ts

This PR aims to correct a typo for the value of `ApiUserAdmin` in `UserGroup` enum.

[#171549167] Fix typo for ApiUserAdmin value in UserGroup enum

---

src/utils/__tests__/documentdb.test.ts
src/utils/documentdb.ts

Our db interfaces return results in the unpleasant form `Promise<Either<QueryError, T>>` while a form `TaskEither<QueryError, T>` would be preferrable. `fromQueryEither` is a helper method that does such type conversion.
This helper [has been used extensively in our codebase](https://github.com/search?q=fromQueryEither+user%3Apagopa&type=Code&ref=advsearch&l=&l=) and it needs to be defined as a common util to avoid duplication.
- Cosmos' query errors are returned as left 
- Runtime errors (that is: when the promise rejects for unexpected problems) are mapped in the form `{code: "error", body: error.message}` to mock the interface of Cosmos' QueryError type
- a convenient `DocumentDbUtils.QueryError` type is defined to map such union 
see [test …

[#173351990] fromQueryEither

---

src/models/__tests__/user_data_processing.test.ts
src/utils/__tests__/cosmosdb_model.test.ts
src/utils/cosmosdb_model.ts

Enforce document IDs as NonEmptyString. This is to avoid manual casting when using objects coming from db (example: fetch a document, edit a field, save the document).
The assumption is safe as `id` field is never empty on Cosmos document. 
What we are losing with these changes is the direct relation between the decoder `ResourceT` and the type `@azure/cosmos/Resource`. This has been mitigated by the introduction of type `ResourceT` and [this cast](https://github.com/pagopa/io-functions-commons/blob/11ae8056e02750220c50eec905f04de1f42a0ae9/src/utils/cosmosdb_model.ts#L45).
`ResourceT` is actually an extension of `@azure/cosmos/Resource`, and hence we should prefer the former to the latter. I see we don't use such kind explicitly in our codebase, though.

[#171554236] Document IDs as NonEmptyString

---

src/utils/__tests__/async.test.ts
src/utils/async.ts

This PR resolve the pending change requests on PR #82

AsyncIterable depends on AsyncIterator utils, remove useless reduceAsyncIterator

---

src/models/__e2e__/integration_tests.ts
src/models/__e2e__/message_integration.ts
src/models/__e2e__/profile_integration.ts
src/models/__e2e__/service_integration.ts
src/models/__e2e__/user_data_processing_integration.ts
src/models/message.ts
src/models/user_data_processing.ts
src/utils/cosmosdb_model_versioned.ts

This PR contains:
- `getNextVersion` bug fix on versioned models that have partitionKey field different from ModelId field
- A binding error fix on `findAllByQuery` method
- Improvement of `createOrUpdateByNewOne` in order to manage correctly upsert operation
- Some integration tests

cosmosDB model bugfix

---

src/utils/__tests__/cosmosdb_model.test.ts
src/utils/cosmosdb_model.ts
src/utils/cosmosdb_model_versioned.ts

Corrects a _what it seems to be_ Typescript unintended behaviour when comparing `undefined` type with other types.
```ts
type Model = { foo: string }
type DSK = DocumentSearchKey<Model, "foo">
// expected: DSK = [string]
// actual: DSK = [string, never]
```
The point is that `PartitionKey` used to have a default on `undefined`, and then we compose `DSK`'s type based on the fact that `PartitionKey extends keyof T` or not. This somehow failed unexpectedly with inconsistent results. 
Instead of using `undefined` as a "not present" placeholder, we now assume that "_no partition key --> partition key is the same of model id_" (which is how Cosmos works, though). Side effect is: 
```ts
type Model = { foo: string }
type DSK1 = DocumentSearchKey<Model, "foo">
type DSK2 = DocumentSearchKey<Model, …
```

[#174189493] DocumentSearchKey type fix

---

src/models/notification.ts
src/models/user_data_processing.ts

Add a partition key to `NotificationModel` (erroneously missing in previous releases)
Plus: better log on bad `UserDataProcessingId`

[#174189493] Fix NotificationModel partition key

---

src/models/__e2e__/profile_integration.ts
src/models/__e2e__/service_integration.ts
src/models/message_status.ts
src/models/notification_status.ts
src/models/profile.ts
src/models/service.ts
src/models/user_data_processing.ts
src/utils/__tests__/cosmosdb_model_versioned.test.ts
src/utils/cosmosdb_model_versioned.ts

This introduces new methods and breaking changes to old ones for the purpose of handling different scenarios explicitly when saving versioned documents.
* ~type `NewVersionedModel` doesn't include `version` field anymore.~
* type `NewVersionedModel` has been removed. `TN` is actually `T`, but it can be extended (to add tags for example).
* `create(o:TN)` creates a new document on db which version is always `0`.
* `upsert(o:TN)` creates a new document on db which version is calculated from the latest document present on db for the same modeld (`0` if no documents are found)
* `update(o: TR)` creates a new document on db which version is calculated as `o.version + 1`

[#174189493] Review CosmosdbModelVersioned public interface

---

openapi/definitions.yaml

This PR allows is_visible to be externally set, by moving it from `Service` to `ServicePayload`.

[#174725389] move is_visible on ServicePayload

---

openapi/definitions.yaml
src/models/service.ts
src/models/visible_service.ts
src/utils/service_metadata.ts

This PR contains a refactoring of `ServiceMetadata` definition in order to add two new fields (e.g `cta`,  `token_name` and `support_url`). Moreover it is used to add a conversion utility for `ServiceMetadata` mapping and an attributes alignment between model and openapi specs.

[#174770172] Service metadata attributes and mapping refactoring

---

package.json
yarn.lock

This fixes a off-by-one in the generation of types for integers and numbers from openapi specs. 
before:
```ts
export const PaymentAmount = 
WithinRangeInteger(1, 1000000000);
```
after:
```ts
export const PaymentAmount = t.union([
WithinRangeInteger<1, 9999999999, IWithinRangeIntegerTag<1, 9999999999>>(
1,
9999999999
),
t.literal(9999999999)
]);
```

BREAKING CHANGE: upgrade italia-utils to fix off-by-one

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml
package.json
yarn.lock

This PR introduces a new definition for `ServicePayload` in order to model the mandatory of service metadata for visible services.
So, the new `ServicePayload`  is valid against one of the following schema:
- `VisibleServicePayload` 
- `HiddenServicePayload`
These definitions differ only for the metadata property, which in the case of `VisibleServicePayload` is required.

[#175160851] Add VisibleServicePayload and HiddenServicePayload definitions

---

.devops/deploy-pipelines.yml

Following the work of #129, I'm trying to get the package published.
In this PR I try to do it with a custom command instead of the built-in `publish` option. This is needed in order to instruct on the access level required by the package (`public`).
Since `io-functions-commons` is a scoped package, as by [npm docs](https://docs.npmjs.com/cli/v6/commands/npm-publish) the default access value is `restricted`. 
I also opened [an issue](https://github.com/microsoft/azure-pipelines-tasks/issues/14165) on the Azure task repo.

[#176013578] Use custom command to publish package

---

src/utils/__tests__/source_ip_check.test.ts
src/utils/source_ip_check.ts

- `authorizedCIDRs` without subnet has default `\32` subnet.
When a Service has an authorized CIDR without a subnet the IPChek fail. This PR adds a default `\32` subnet.
- unit test

[#ENTE-20] AuthorizedCIDRs without subnet

---

.devops/deploy-pipelines.yml
package.json

Include OpenAPI definitions in published package so that they can be used by its dependents, if in need.
**Expected usage**
```yaml
Foo:
$ref: "./node_modules/@pagopa/io-functions-commons/openapi/definitions.yaml#Foo"
```

[#IP-163] Include OpenAPI spec file in package

---

src/models/__tests__/user_data_processing.test.ts
src/models/user_data_processing.ts

I decided to revert what has been made in #142. 
I firmly believed we should model the `reason` field to exist for `FAILED` records only. With such convincement, I led @michaeldisaro into a complex codec definition that would satisfy the need of type-soundness. 
As a matter of fact, it turned out this interface to be at least impractical if not dangerous, even. 
With this PR I'm reverting such changes and define `reason` field as optional for any status. As it makes sense for `FAILED`s only, I also remove such field from creation when needed.

[#IP-144] Re-model reason field as an optional field

---

.devops/code-review-pipelines.yml
__integrations__/models/cosmos_utils.ts
__integrations__/models/message.test.ts
openapi/definitions.yaml

Allow a `Message` to accept a `eu_covid_cert` field in its content. 
An example of value could be:
```json
"eu_covid_cert": {
"auth_code": "nk34nidwew9o4nro3noionwow"
}
```
Which will be included in a `Message` as 
```json
{
"content": {
"subject": "Certificato Europeo Covid-19",
"markdown": "Visualizzare il tuo Certificato Europeo Covid-19. Per visualizzare il certificato è necessario aver installato l'ultiva versione dell'App IO.",
"eu_covid_cert": {
"auth_code": "nk34nidwew9o4nro3noionwow"
}
},
"fiscal_code": "AAAAAA00A00A000A"
}
```

[#IP-203] Add message payload for EU Covid Certificate

---

src/utils/middlewares/__tests__/azure_api_auth.test.ts
src/utils/middlewares/azure_api_auth.ts

Add a middleware that allow a specific payload to be provided only by a specific set of user groups.
It is designed for when it's needed to allow only a subset of users to provide a payload that matches a specific subset of the payload schema.
The use case is: we want restrict the opportunity to send a specific field into a Message content to a limited group of users.

[#IP-215] Add AzureAllowBodyPayloadMiddleware

---

package.json
yarn.lock

- Removed io-functions-express from dependencies
We want to keep dependencies updated and coherent between projects.
This dependency was not used and was causing cross-repo conflicts.
It has been tested by performing:
- yarn install --frozen-lockfile
- yarn build
- yarn lint
- yarn test

[#IP-223] Removed io-functions-express from dependencies

---

.github/PULL_REQUEST_TEMPLATE.md
__integrations__/models/profile.test.ts
openapi/definitions.yaml
src/models/__tests__/profile.test.ts
src/models/profile.ts

* introduce `LEGACY` preferences mode to map Profiles with old schema in [`99b10ab` (#185)](https://github.com/pagopa/io-functions-commons/pull/185/commits/99b10ab078ea862a8b6e3a5c81cecb03525f1d5c)
* test all modes are considered in [`ddeaee8` (#185)](https://github.com/pagopa/io-functions-commons/pull/185/commits/ddeaee8572f735f09f4d808219a5dbbb8865949b)
* add integration tests for negative scenarios in [`6b67655` (#185)](https://github.com/pagopa/io-functions-commons/pull/185/commits/6b67655825cea1b2474dc3c976bf900e86332eff)
* (chore) add PR template in [`5fc1af5` (#185)](https://github.com/pagopa/io-functions-commons/pull/185/commits/5fc1af519b1fcc3f55fc384a95f4044736459575)
We recognized we need an explicit definition for Citizens whose `Profile` hasn't switched to new preferences …

Bugfix missing LEGACY preferences mode

---

src/utils/cosmosdb_model.ts

When dealing with a query with more than a result, we need to get access to results' metadata such as `hasMoreResults` and `continuationToken`. Cosmosdb's SDK provide such informations in its [`FeedResponse` response object](https://github.com/Azure/azure-sdk-for-js/blob/e823b26f4600a698eb1c06f48da9b780fb2331a7/sdk/cosmosdb/cosmos/src/request/FeedResponse.ts#L6); so far, we decided to strip metadata off the results, so to have a cleaner data structure (see [here](https://github.com/pagopa/io-functions-commons/blob/0785e81b4aba3e00e37936cacba5305b133cdc08/src/utils/cosmosdb_model.ts#L261)).
We are now going back on this decision, having query results to come with their metadata. `DecodedFeedResponse` is an interface that mimics `FeedResponse` in naming, but adds a couple of features:
* …

Add `DecodedFeedResponse` type definition

---

src/models/__tests__/service.test.ts
src/models/service.ts
src/utils/async.ts

Add new method `listLastVersionServices` in `Service` model to get the last version of all services in cosmos
To generate services webview and services list into the IO website we need do retrieve all the services from cosmos.
Unit test

[#ENTE-79] listLastVersionServices in Service model

---

src/utils/__tests__/async.test.ts
src/utils/async.ts

This PR is related to https://github.com/pagopa/io-functions-commons/pull/207, to discuss about whether we need `asyncMapAsyncIterator` or not

[#IP-362] Message enrichment - add on

---

__integrations__/models/cosmos_utils.ts
__integrations__/models/message.test.ts
src/models/__tests__/message.test.ts
src/models/message.ts

- fixed query to order by fiscalCode other than by id to use the new composite index
- modified container init function of integrations' tests to accept an indexing policy
Order by id kills cosmosdb performance on huge collections. With the composite index and ordering we avoid this issue.
- yarn lint
- yarn build
- yarn test

[#IP-405] Fixed messages query to use index

---

src/utils/middlewares/azure_api_auth.ts

This PR adds a new group to allow payee payload only for selected services/users
- `azure_api_auth.ts`
This is needed to avoid that every one with Message Write permission could send payment message with payee.

[#IP-189] Add specific group for payment messages with payee

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml

- definitions.yaml
- definitions.test.ts
This is needed for exposing the correct shape for the model exposed by `GetMessage` API. Since for a payment message we should always return payee, we have to change `CreatedMessageWithContent` definition in order to make payee required in `PaymentData`
unit test

[#IP-184] Add paymentData with Payee on GetMessageModel

---

src/utils/__tests__/cosmosdb_model_composed_versioned.test.ts
src/utils/cosmosdb_model_composed_versioned.ts
src/utils/cosmosdb_model_versioned.ts

A new model type is created `CosmosdbModelComposedVersioned`.
Refactory of `CosmosdbModelVersioned` to allow override of `createNewVersion` method.
We need a new model type that handle versioning for documents with a couple externalKey-partitionKey.
This model works correctly with a limited range of externalKey for a specific partition key.
unit test

[#IC-50] Composed Cosmos Versioned Model

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml
src/models/__tests__/notification_event.test.ts
src/models/__tests__/service.test.ts
src/models/created_message_sender_metadata.ts

1. `ServiceMetadata` decoder can successfully decode a `Service` with an unknown service category. The `category` will be ignored.
2. `ServicePayload` accept only `CommonServiceMetadata` without category.
1. The changes to `ServiceMetadata` allow unupdated apps to decode services with unknown category. This is needed to avoid forced mobile app upgrade when a new category is introduced.
2. Only Admin user can create or modify services category. Admin will use `Service` type instead other user will use `ServicePayload` type.
unit test

[#IC-89] App can decode unsupported service category

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml
src/utils/middlewares/azure_api_auth.ts

Message body needs a new optional block in order to store the info required by "Messaggi a Valore Legale" project.
To allow senders to fill this block, a new permision has been added.
Add LegalData definition to openapi
Add ApiMessageWriteWithLegal permission to api auth
We needs to store the minimum info to retrieve a MVL from a PEC-SERVER.
unit test

[#IC-66]  Add Legal Data to message model and write permission

---

openapi/definitions.yaml

The Legal Message could be sent to IO by different PEC-SERVER. IO must store the PEC-SERVER sender ID in order to properly manage message nerichment.
Add pec_server_service_id to message legal_data
Currently we do not store any info about PEC-SERVER message sender
Unit test

[#IC-206] Enable multi-provider for Legal Message

---

src/utils/__tests__/record.test.ts
src/utils/record.ts

When patching a cosmos nested object, the field name with . is not properly managed.
Fixed switching to _/_ delimiter.
Replaced delimiter on patch
Proper manage nested object
unit test
system test

[#IC-394] Wrong cosmos inner field naming on patch 

---

src/models/__tests__/message_view.test.ts
src/models/message_view.ts

Add a default for third_party component in the message_view decoder in order to decode legacy view documents. The default will be "NotHasComponent" becouse legacy documents could never contains a third_party data,
Add default to third_party component on message_view decoder
This default will allow us to decode legacy view documents without re-build the entire view.
unit test

[#ICC-84] Add NotHasComponent as default for third_party component in message_view

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml

`last_app_version` field is a pattern string instead a `x-import` of `Semver` from `@pagopa/ts-commons`
The IO App cannot update `ts-commons` to import `Semver` for compatibility issues.
unit test

[#IOCIT-27] Change AppVersion definition with pattern instead x-import

---

__integrations__/models/message.test.ts
src/models/__tests__/message.test.ts
src/models/message.ts
src/utils/__tests__/azure_storage.test.ts
src/utils/azure_storage.ts

The getContentFromBlob method of Message model do not set apart empty blob from not existing blob. A not exisitng blob should not throw and error, becouse a message without content is valid.
add new getBlobAsTextWithError to azure utils
change getContentFromBlob method to manage 404 get blob error
The message model is used to retrieve a message. A Service poll this method via fn-service API to known the status message as part of send message process. This polling must return a message without content if the message is not rejected/refused, but not yet processed.
unit test

[#ICC-167]  Fix get message error 500 when retrieving message without content

---

__integrations__/models/message-status.test.ts
openapi/__tests__/definitions.test.ts
openapi/definitions.yaml
src/models/__tests__/message_status.test.ts
src/models/__tests__/message_view.test.ts
src/models/message_status.ts

Add `rejection_detail` to `MessageStatus`when status is `REJECTED`. 
RFC 9012- We need to distinguish the reason of a rejected message. A message can be rejected because recipient is not a user of IO, or because the service is not allowed to contact that user.
Unit tests

[ICC-195] Add rejection_detail to MessageStatus

---

__integrations__/models/profile.test.ts
openapi/definitions.yaml
src/models/__tests__/profile.test.ts
src/models/profile.ts

- Added `reminderStatus` property with an `UNSET` default to `profile` model
- Added `reminderStatus` openapi specs
- Added `reminder_status` to `Profile` and `ExtendedProfile` openapi specs 
- Added tests
We need to allow user to express his will about opting in to reminder feature.
- yarn build
- yarn lint
- yarn test

[#IOCIT-112] Added properties for reminder opt in

---

openapi/definitions.yaml
src/models/profile.ts

Removed UNSET value from API specs of Reminder Status and kept it as a model's only property value.
We don't want the mobile app to deal with the UNSET value. Mobile app will receive an `undefined` when no reminder status has been set while model on cosmos db will track the new property for every profile by setting an `UNSET` default.
* yarn build
* yarn test
* yarn lint

[#IOCIT-112] Removed UNSET value from API specs of Reminder Status

---

__integrations__/models/profile.test.ts
openapi/definitions.yaml
src/models/__tests__/profile.test.ts
src/models/profile.ts
src/utils/types.ts

* added `pushNotificationsContentType` optional field to the profile model
* added `push_notifications_content_type` optional field to the OpenAPI spec(in particular to the `Profile` and `ExtendedProfile` definitions)
allow user to specify how to visualize the push notifications
build passed 
unit and integration tests passed

[#IOCIT-137] Add pushNotificationsContentType optional field to the profile model

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml

* [Add has_precondition flag to ThirdPartyData](https://github.com/pagopa/io-functions-commons/commit/2b56070bd2f2b921a9a5c81dd87cd217c1f2c20c);
Third party should be able to specify preconditions during the CreateMessage
Unit test.

[#IOCOM-556] Add has_precondition flag to ThirdPartyData

---

openapi/definitions.yaml

* [Fix openapi descriptions](https://github.com/pagopa/io-functions-commons/commit/4a8f6a75592e6f4d680dea19dab9e8fcedf54ad2);
No tests are needed.

[#IOCOM-671] Fix openapi descriptions

---

src/models/__tests__/remote_content_configuration.test.ts
src/models/remote_content_configuration.ts

Added new model 
Added tests
We need a new model to retrieve Remote Content Configuration
yarn install
yarn lint
yarn build
yarn test

[#IOCOM-729] Added new RemoteContentConfiguration model and tests

---

src/utils/unique_email_enforcement/index.ts
src/utils/unique_email_enforcement/storage.ts

1. removed the possibility to filter the `uniqueEmails` table by its row key
filter a table for a row key is an expensive operation, that it is not justified by practical reasons

[IOPID-1245] Remove fiscal code filter to avoid full table scan

---

src/utils/unique_email_enforcement/__tests__/index.test.ts
src/utils/unique_email_enforcement/__tests__/storage.test.ts
src/utils/unique_email_enforcement/index.ts
src/utils/unique_email_enforcement/storage.ts

Added `get` method to `IProfileEmailReader` interface and to the `DataTableProfileEmailsRepository` implementation
This method is needed in the `OnProfileUpdate` function to get the entity from `(partitionKey, rowKey)`
Through unit tests

[#IOPID-1197] Add get method to table storage model

---

src/utils/unique_email_enforcement/__tests__/index.test.ts
src/utils/unique_email_enforcement/__tests__/storage.test.ts
src/utils/unique_email_enforcement/index.ts
src/utils/unique_email_enforcement/storage.ts

1. add `cause` field on error throws by `DataTableProfileEmailsRepository`'s `delete` and `insert`
2. remove `get` method
with this change we can achieve better error handling
- [] Bug fix (non-breaking change which fixes an issue)

feat(uee): [IOPID-1325] add DataTableProfileEmailsRepository error cause

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml

- [added configuration_id in ThirdPartyData as an ulid](https://github.com/pagopa/io-functions-commons/commit/09d963e95af3372a778f6c1c2dd06f3b62f2ccf3)
- [added test for configuration_id in ThirdPartyData](https://github.com/pagopa/io-functions-commons/pull/356/commits/02a1b9092219c725ebfbb8a75f02cb3fc4a1567c)
Added an optional configuration id in the ThirdPartyData in order to make it possibile to be sent in the CreateMessage

[#IOCOM-962] added configuration_id in ThirdPartyData as an ulid

---

openapi/definitions.yaml

[#IOCOM-1020] modified rc configuration definitions for crud api

---

openapi/definitions.yaml

We need this property to be outside of NewRCConfigurationBase in order to manage operations of create and update
* [Extract userId from NewRCConfigurationBase](https://github.com/pagopa/io-functions-commons/commit/bb5e835ca4b0f8aafaa429733c58322c3a0fcf4d)

[IOCOM-1030] Extract userId from NewRCConfigurationBase

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml
src/models/__tests__/rc_configuration.test.ts
src/models/rc_configuration.ts
src/utils/rc_configuration.ts

* [Update definitions and fix unit test](https://github.com/pagopa/io-functions-commons/commit/f25b207da3d7783c82eda974eb571fb95282ee80);
* [Update rc-model in order to accept partial environment](https://github.com/pagopa/io-functions-commons/commit/b4c8bab06fd7cbe42b2af90faa11f95787f069ad);
* [Fix mappers](https://github.com/pagopa/io-functions-commons/commit/8ab0a6336e98ee9d6f82eeaaa14bfcd7f17e0b45).
We need to make those properties optional
Unit test

[#IOCOM-1074] Make RCConfigurationEnvironment optional

---

openapi/definitions.yaml

- [fix remote content configuration definitions](https://github.com/pagopa/io-functions-commons/pull/366/commits/d9a74764b34f7e9d987f488f9427eb8ed41f7ad8)
Added new remote content configuration model to manage request and response

[#IOCOM-1047] fix remote content configuration definitions

---

src/utils/__tests__/cosmosdb_model.test.ts
src/utils/cosmosdb_model.ts
src/utils/cosmosdb_model_versioned.ts

I propose a fix on #371 
The `DocumentSearchKey` type ensures we query database object by fields whose type is `string` (for model id) or `string | number` (for partition key)

[DEVEX-106] Fix proposal

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml

* Add a new definition `EnrichedMessageWithOrganizationFiscalCode`;
* Add unit test for the new definition;
* Add missing unit test for `BaseEnrichedMessage`
We need to add the `organization_fiscal_code` when the `GetMessages` is called with the enrichment flag = `true`.
Unit test.

[IOCOM-1243] Add organization_fiscal_code to the PaginatedPublicMessageCollection

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml

* Revert changes made in #379;
* Add organization fiscal code in `EnrichedMessage`;
* Add unit test for `EnrichedMessage` definition;
Since io-app also need the organization fiscal code when calling GET `/messages/{id}` there is no need to add the definition `EnrichedMessageWithOrganizationFiscalCode` added in #379, we can simply add the `organization_fiscal_code` in the `EnrichedMessage` definition which is used to compose  `PaginatedPublicMessagesCollection` (the type of the response of GET `/messages/{fiscalCode}`) and `InternalMessageResponseWithContent` (the type of the response of GET `/messages/{id}`).
Unit test.

[IOCOM-1462] feat: Add organization fiscal code in EnrichedMessage
