src/utils/azure_storage.ts

Allow options in acquireLease/releaseLease functions

---

openapi/definitions.yaml
src/models/profile.ts

I am splitting #31 in 2 parts.
First part here.

[#168821506] Profile with is_email_validated field

---

src/entities/validation_token.ts
src/utils/azure_storage.ts

I am splitting #31 in 2 parts.
Second part here.

[#168821506] Add ValidationToken entity

---

src/utils/middlewares/azure_api_auth.ts

This PR aims to add some new user groups to allow services list, api keys read and api keys write

[#170129433] Add user groups to list services, read api keys, write api keys

---

src/models/__tests__/profile.test.ts
src/models/profile.ts

Set isEmailEnabled = true and isEmailValidated = true when undefined into the user's profile stored into the database.

[#171688229] add defaults for isEmailEnabled / isEmailValidated

---

openapi/definitions.yaml
src/models/service.ts
src/models/visible_service.ts

Add `requireSecureChannels` to visible service model, in order to compute available_notification_channels for ServicePublic

[#171684904] add requireSecureChannels to visible services

---

openapi/definitions.yaml
src/models/__tests__/profile.test.ts
src/models/profile.ts

Added isTestUser flag to Profile in order to enable login without SPID/CIE for testing purpose.

[#172376369] Add test profile flag

---

openapi/definitions.yaml

Add ABORTED state to UserDataProcessingStatus

[#173769740] add ABORTED state to UserDataProcessingStatus

---

src/utils/__tests__/async.test.ts
src/utils/async.ts

Allow mapping AsyncIterator with Either values
Allow flat AsyncIteretor with Readonly Array

Add AsyncIterator / Iterable map, reduces, flatten

---

src/models/visible_service.ts

Removed intersection with RetrievedVersionedModel

VisibleService model definition refactor

---

src/utils/__tests__/cosmosdb_model_versioned.test.ts
src/utils/cosmosdb_model_versioned.ts

Changes the behaviour of `CosmosdbModelVersioned.upsert` to implicitly increment the version of the provided document.

[#174189493] Upsert to increment version implicitly

---

src/models/message.ts

This PR includes a better exception wrapping on `findMessages` method

Model's methods minor refactoring

---

openapi/definitions.yaml

Split Service definition in:
ServicePayload: used to create/update service in services function
Service: used as return type in get/create/update in services function, used as create/update type in admin function

Create ServicePayload definition

---

yarn.lock

We still have to solve the alert on "azure-storage" but it needs the migration versus the new SDK.

Solve many Snyk alerts

---

src/templates/html/default.ts
templates/mjml/default.mjml

A minimal fix to generated style on email template.

[#169589538] Fix mjml raw template styling

---

openapi/definitions.yaml

switched _sender_service_id_ from string to **ServiceId** type into **CreatedMessageWithoutContent** and **CreatedMessageWithContent** types.

[#171207518] switched sender_service_id from string to ServiceId type

---

package.json

[#176013578] Remove prepack script

---

src/models/service.ts

Create a new Type `ValidService` with required metadata for production.
A Services that haven't the required metadata information can't be enabled to send message to users.
The quality requirements for a Service are:
- Almost one `authorizedCIDR`
- The Service description
- The `privacyUrl`
- Almost one contact information (`email`, `pec`, `phone`, `supportUrl`)
no tests

[#ENTE-82] New ValidService type

---

src/models/__tests__/service_preference.test.ts
src/models/service_preference.ts

Change `getServicesPreferencesDocumentId` into `makeServicesPreferencesDocumentId`

Rename function `makeServicesPreferencesDocumentId`

---

package.json
src/utils/azure_storage.ts
src/utils/cosmosdb_model.ts
yarn.lock

- Upgrade typescript to v ^4.3.5
- Fix build errors
Upgrade ts
Unit tests

[#IP-326] Upgrade Typescript to version 4.3.5

---

src/utils/cosmosdb_model.ts

Reverts pagopa/io-functions-commons#197

Revert "Add `DecodedFeedResponse` type definition"

---

__mocks__/mocks.ts
src/models/__tests__/visible_services.test.ts
src/models/visible_service.ts

Replaced StrMap with ReadonlyMap because it's been removed from fp-ts 2.x
Upgrade to fp-ts 2.x
* yarn test

[#IP-379] Replaced StrMap with ReadonlyMap

---

package.json
src/utils/response.ts
yarn.lock

* refactored `items_size` to `page_size` for paged response
* updated ts-commons to latest version (just for coherence)
I wanted to keep coherence with the old json iterator response.
* yarn build
* yarn test
* yarn lint

[#IP-362] Minor fixes

---

openapi/definitions.yaml

Changed openapi spec for PaginatedResponse to add actual pagination fields.
Added openapi spec for EnrichedMessage and relative Collection to allow for content enrichment.
These changes are required for messages pagination and enrichment with content.
* yarn build
* yarn test

[#IP-362] Added openapi pagination

---

src/utils/__tests__/healthcheck.test.ts
src/utils/healthcheck.ts

Added base healtcheck functions, common to all Azure Functions projects.
Usage:
```` typescript
pipe(
getConfig(),
//     ^^^ the env config (with `azureStorageUrl` and `anUrlToCheck`)
checkApplicationHealth(IConfig, 
//                            ^^^ the io-ts Codec
[
c => checkAzureStorageHealth(c.azureStorageUrl),
c => checkUrlHealth(c.anUrlToCheck)
]
//       ^^^ a list of checks, built with decoded config and one of the base check functions
),
...
);
````
Remove duplicated code
unit tests

[IP-385] healtcheck function commons to all azure function implementation

---

src/utils/middlewares/__tests__/optional_query_param.test.ts
src/utils/middlewares/optional_query_param.ts

Added a middleware that checks for query params and map them to optionals if not present.
Added tests for this middleware.
We need some optional query params to enable message pagination and message enrichment.
* yarn build
* yarn test
* yarn lint

[#IP-362] Added middleware to map query params to optionals

---

openapi/definitions.yaml

Fixed name in openapi model to be snake_case.
yarn build
yarn test
yarn lint

[#IP-362] Fixed hasMoreResults to has_more_results

---

src/utils/healthcheck.ts

- Fix healthcheck signature
- Add `AzureNotificationHub` in ProblemSource literal type
- Export `toHealthProblems` to enable importing projects to add their own healthcheck implementations (like Azure Notification Hub one) 
Unit tests

[#IP-389]  Improve healthcheck

---

__integrations__/models/activation.test.ts
openapi/definitions.yaml
src/models/__tests__/activation.test.ts
src/models/activation.ts

Create `ActivationModel` from `CosmosdbModelComposedVersioned`
To store services Activation for SpecialServices is introduced a new `ActivationModel`. This model handle versioning of documents identified by the tuple `fiscalCode` and `serviceId`.
unit test
integration test

[#IC-51] Activation model

---

openapi/definitions.yaml

Added openapi definitions for MessageCategory to be used in message categorization.
We need to return message category during message enrichment.
* yarn build
* yarn test
* yarn lint

[#IC-100] Added openapi for MessageCategory

---

openapi/definitions.yaml

[#IC-100] Fixed green_pass category to eu_covid_cert

---

src/utils/source_ip_check.ts

- `checkSourceIpForHandler` now supports up to 7 middleware
We have to apply ip check logic to a new handler with 7 middleware.
Btw we have to refactor this in the near future in order to make it more extensible.

add support for other middleware in Ip check

---

openapi/definitions.yaml
src/utils/middlewares/azure_api_auth.ts

- `ImpersonatedService` now has user_email required attribute
- Added new User Group to avoid sending MVL directly without impersonification
Required by MVL POC

[#IC-131] Add email to impersonated service and new group

---

openapi/definitions.yaml
src/utils/activations.ts

`Activation` definition for `GetActivation` and `UpsertActivation` API
`ActivationPayload` definition for `UpsertActivation` payload
The new API in `io-functions-services` needs two new type definition for the responses and the payload. These new type are added with this PR.
not tested

[#IC-52] Add Activation API type definitions

---

src/utils/__tests__/healthcheck.test.ts
src/utils/healthcheck.ts

* Replace union of specific string literals with any string literal

Make HealthChecks extensible

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml

Added a MessageStatusAttributes model.
Redefined MessageStatus by including MessageStatusAttributes with defaults.
We need a new model to define if a message has been read and/or archived.

[#IC-329] Addition for message status attributes update

---

__integrations__/models/message-status.test.ts
src/models/__tests__/message_status.test.ts
src/models/message_status.ts

- Added "isRead" and "isArchived" attributed in MessageStatus model (with `false` as default)
- Updated tests
Messages pagination and server-side filtering
Unit tests

[#IC-313]  Update `message-status` model

---

package.json
yarn.lock

Update the azure/cosmos library to provide _patch_ feature used for document partial update
Update cosmos version to 3.15.1
The current version do not implement the _patch_ operation: in order to update a document value we have to retrieve the whole document before. The partial update operation will allow us to increase data cleasing and materialize view update performance
unit test

[#IC-354] Update cosmos lib to 3.15.1

---

src/models/__tests__/message_view.test.ts
src/models/message_view.ts

The message_view collection will be used to materialize all the metadata used by IO-App search feature.
This view will allow us to query only one cosmos collection instead of the current enrichment process (cosmos+storage).
Add message_view model
The current message pagination could not provide the currently implemented search feature in app.

[#IC-304] Add message_view model

---

src/utils/__tests__/cosmosdb_model.test.ts
src/utils/cosmosdb_model.ts

- add `condition` to patch operation
This is needed in order to support conditional patching at cosmos level

[#IC-380] Add support for condition in patch operation

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml
package.json

Extends MessageStatus with MessageStatus Attributes
This extends MessageStatus model in order to make return type of upsert endpoint more RESTFul
Unit

[#IC-384] Add MessageStatusWithAttributes

---

src/models/__tests__/message_view.test.ts
src/models/message_view.ts

Add notice_number from payment message content to mesage_view.
add notice_number
do not retrieve message content from blob to enrich message metadata 
unit test

[#IC-383] Add notice_number to message_view

---

src/utils/messages.ts

- add `time_to_live` value to retrievedMessageToPublic result

[#IC-398] add time_to_live value

---

src/utils/middlewares/azure_api_auth.ts

- Add read/write user group for advanced features
Advanced message handling
-

[#IC-425] Add read/write user group for advanced features

---

__integrations__/models/message.test.ts
openapi/definitions.yaml
src/models/__tests__/message.test.ts
src/models/message.ts

- Add featureLevelType on definitions
- Add featureLevelType on message model
- Add tests
This is needed in order to enable advanced feature on messages.
Unit test and integration tests.

[#IC-424] Add featureLevelType on Message Model

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml

This PR depends on #260 
- `feature_level_type` property added to `NewMessage` (optional)
Advanced message handling
Unit tests

[#IC-441] add feature_level_type to NewMessage model for CreateMessage endpoint

---

__integrations__/models/message-status.test.ts
openapi/definitions.yaml
src/models/__tests__/message.test.ts
src/models/__tests__/message_status.test.ts
src/models/message_status.ts

- Add paymentStatus to messageStatus
- Add paymnetStatus definitions
- Add tests
This is needed in order to store paymnet status for all messages that are related to a debt position
unit and integration tests

[#IC-442] Add Payment Status to Message Status model

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml
src/utils/messages.ts

This PR depends on #261 
- add `feature_level_type` to `CreatedMessageWithContent` and `CreatedMessageWithoutContent`
- add `ReadStatus` definition
- update tests
Advanced messages

[#IC-427]  Update GetMessage definitions

---

__integrations__/models/message-status.test.ts
src/models/__tests__/message_status.test.ts
src/models/message_status.ts

Remove paymentStatus from MessageStatus model
Payment status needs its own model
Unit tests

[#IC-453] Remove paymentStatus from MessageStatus model

---

src/models/__tests__/message_view.test.ts
src/models/message_view.ts

- Add payment_status to message view 
This PR is needed because we need to align information about payment status related to a specific notice number / message.
This alignment could be useful for presenting informations directly.
Unit test

[#IC433] Add payment_status to messageView

---

openapi/definitions.yaml

[FIX] read status description

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml
src/utils/messages.ts

- new "External" definitions
Fix definitions to avoid new fields to be returned by fn-app-messages' GetMessage implementation
Unit test

[Fix] Update created message definitions

---

openapi/definitions.yaml

- `definitions.yaml` refactored with `GetMessageResponse`
This PR is needed for expose EnrichedMessage Properties in GetMessage endpoint

[#IC-456] Add Enriched Properties to GetMessage

---

openapi/definitions.yaml

[#IC-456] Add Enriched to Get Message Response

---

src/utils/middlewares/azure_api_auth.ts

- Add ApiThirdPartyMessageWrite
This new group is needed in order to authorize 3rd parties to send a specific kind of message
No tests needed

[#ICC-85] Add Group for third party message write

---

src/models/__tests__/message_view.test.ts
src/models/message_view.ts

- add due_date to PaymentComponent in message-view model
- add tests
This is required because of new payment info to be returned by the message view
Unit

[#ICC-104][#ICC-114] Add Due Date to Payment Component in Message View

---

.gitignore
README.md
__integrations__/models/cosmos_utils.ts
__integrations__/models/profile.test.ts
openapi/definitions.yaml
package.json
src/models/__tests__/profile.test.ts
src/models/profile.ts
yarn.lock

Added `lastAppVersion` optional field to Profile type
Add `last_app_version` optional field to Profile API definitions
Add `last_app_version` optional field to ExtendedProfile API definitions
update `openapi-codegen-ts` to last version
Add a field to the citizen profile template that tracks the last APP version
Profile model unit test
Profile model integration test

[#IOCIT-8] Add lastAppVersion optional field to profile type

---

package.json
yarn.lock

1. Update `@azure/functions` to its latest version
This project used a long outdated version of `@azure/functions` which interferes with new projects that use more recent versions of the package.
This dependence has no impact on runtime because it simply contains type definitions. Unit tests are still functional after the upgrade.

chore(deps): update @azure/functions

---

src/utils/middlewares/__tests__/azure_api_auth.test.ts

Add test for AzureApiAuthMiddleware to prove the compatibility with enum and t.literal i the matching model.
This will be used by notify endpoint to provide a role access based on the value of the template filed in the request body.
add unit test to azure api auth

[#ICC-205] Add test to for literals and enum to azure api auth middlewere

---

src/utils/middlewares/azure_api_auth.ts

Add new user group to provide access to notify feature based only for specific role/template combinations. This will allow us to control which API users could send push notification using what message.
add user groups for API notify
Prevent misuse of notify enpoint.

[#ICC-233] Add user groups for notify templates

---

src/models/__tests__/profile.test.ts

* ported old commented profile model tests
restore the commented tests
tests passing

[#IOCIT-117] ported old commented tests

---

src/utils/cosmosdb_model_versioned_ttl.ts

add a cech between the records found by the findallVersions and the batch operation for the update ttl function for versioned model.
see commit history
a better management of batch errors

Add cardinlaty check on batch for update ttl

---

__integrations__/models/message-status.test.ts
src/models/__tests__/message_status.test.ts
src/models/message_status.ts
src/utils/cosmosdb_model_ttl.ts

* Add `ttl` to `MessageStatusUpdate`;
* Add unit test;
* Add integration test;
In order to directly create message status entries with the `ttl` property, we want to add it into the `MessageStatusUpdate`.
unit and integration tests

[IOCIT-194] Add ttl to MessageStatusUpdate

---

src/utils/cosmosdb_model_ttl.ts

Fix ttl type

---

package.json
yarn.lock

[#IOCIT-174] - Upgrade request-ip

---

.devops/code-review-pipelines.yml
.github/workflows/pr-title-linter-and-linker.yaml
Dangerfile.ts
openapi/definitions.yaml
package.json
yarn.lock

[#IOCIT-277] Added Ulid to definitions

---

src/utils/middlewares/__tests__/azure_user_attributes_manage.test.ts
src/utils/middlewares/azure_user_attributes_manage.ts

New middleware for MANAGE Flow
Added new AzureUserAttributesManageMiddleware
In order to use *Manage Api Key* for *Services Create/Update*, we need a new middleware for checking user permissions

[#IOPAE-140] New Manage Flow Middleware

---

src/utils/__tests__/healthcheck.test.ts
src/utils/healthcheck.ts

Fix HealthCheck CosmosClient management

---

.devops/code-review-pipelines.yml
openapi/__tests__/lollipop_definitions.test.ts
openapi/definitions.yaml
openapi/lollipop_definitions.yaml
package.json

- Add new `lollipop_definitions.yaml`
- Add test
- Add `ApplicationInfo` definitions
Lollipop Protocol

[#IOCIT-294]  Add LolliPoP common definitions

---

.devops/deploy-pipelines.yml

Add lollipop_definitions.yaml to package

fix: [#IOCIT-292] Add lollipop_definitions.yaml to package

---

src/utils/cosmosdb_model.ts

New `CosmosConflictResponse` value for handle conflict responses in `CosmosErrors`
CosmosErrors doesn't have a support for conflicts errors. This PR extend the type, not yet implement the error parsing for conflict responses from the SDK.
not needed

Add new Cosmos conflict response to CosmosErrors

---

src/entities/revoke_assertion_ref_info.ts

Add the entity `RevokeAssertionRefInfo`, sent through LolliPoP revoke queue
LolliPoP management

[#IOCIT-354] Add RevokeAssertionRefInfo entity

---

__mocks__/mocks.ts
openapi/__tests__/lollipop_definitions.test.ts
openapi/lollipop_definitions.yaml

Add AssertionFileName common definition

---

src/utils/__tests__/source_ip_check.test.ts
src/utils/source_ip_check.ts

Update **source_ip_check** with subscription manage authorized cidrs
- src/utils/source_ip_check.ts
We need to limit the use of Manage Subscription key to an authorized IP List (in CIDRs format).
unit tests

[#IOPAE-196] update client ip and cidr tuple

---

src/utils/transports/application_insight.ts

Remove name from properties of winston-tranport

---

src/utils/__tests__/crypto.test.ts
src/utils/crypto.ts

Copy crypto functions from `io-functions-lollipop` and `io-backend`.
Avoid code duplication across repos.
unit test

[#IOPID-127] Porting `content-digest` crypto fn from `io-functions-lollipop`

---

openapi/__tests__/definitions.test.ts
openapi/definitions.yaml

- [new category field in ThirdPartyAttachment](https://github.com/pagopa/io-functions-commons/commit/0b6254fa8a8f47952dd7696751ed6814cbf837d2)

[#IOCOM-566] new category field in ThirdPartyAttachment

---

openapi/definitions.yaml

- [new UrlSafeServiceId definition](https://github.com/pagopa/io-functions-commons/commit/4606812633261ea08bf33bbe7ac597948d3a210e)
Created a new definition for a url safe the service_id that goes in the parameter

[#IOCOM-151] new PathTraversalSafePathParam definition

---

openapi/definitions.yaml
openapi/problemJson_definitions.yaml

- Add `IsEmailAlreadyTaken` definition, with false as default
- Add `is_email_already_taken` to `ExtendedProfile`
- Add `UpdateProfile412ErrorTypes` enum
Implementing email uniqueness checks

[#IOPID-1045] Update Profile definitions

---

openapi/definitions.yaml

[#IOCOM-710] Add RC details

---

src/models/__tests__/message_view.test.ts
src/models/message_view.ts

- [added new flags for remote content](https://github.com/pagopa/io-functions-commons/commit/460fdc9ef9b5b5f57940cd184ff66868071262ae)
Added new flags has_remote_content and has_precondition in message view model to manage the remote content messages

[#IOCOM-708] added new flags for remote content

---

src/models/__tests__/remote_content_configuration.test.ts
src/models/remote_content_configuration.ts

Fixed case for some properties to make it coherent
We need coherent code
unit tests

[#IOCOM-729] Fixed property case

---

openapi/definitions.yaml
src/utils/__tests__/async_iterable_task.test.ts
src/utils/async_iterable_task.ts

- add new `async_iterable_task.ts` file, already tested on fn-app-messages and io-backend
- add tests
Refactor to reduce code duplication
Unit tests

[#IOPID-1111] Add async iterable task utilities + tests

---

openapi/definitions.yaml
src/models/__tests__/rc_configuration.test.ts
src/models/message_view.ts
src/models/rc_configuration.ts
src/models/remote_content_configuration.ts

- [new definitions for the remote content configuration apis](https://github.com/pagopa/io-functions-commons/pull/358/commits/ff121cb9635b308ab09c44d80940e887fa549c9b)
- [fixed string field with minLength for rc configuration](https://github.com/pagopa/io-functions-commons/pull/358/commits/ad90df72b7840f325e5f19ad62831e355f1cba77)
- [small fix](https://github.com/pagopa/io-functions-commons/pull/358/commits/a044867dd99d53e5eb29e44eed8950a96b874397)
Added definitions to manage the model of the remote content configuration and the response of the GetRCConfiguration api

[#IOCOM-921] new definitions for the remote content configuration apis

---

src/models/__tests__/message_view.test.ts
src/models/message_view.ts

[#IOCOM-1041] added configuration_id field in message_view

---

src/models/rc_configuration.ts
src/models/remote_content_configuration.ts

Fixed the name of a collection.
Added a remind comment.
There was a wrong name.

[IOCOM-755] Fixed collection name

---

__integrations__/models/rc_configurations.test.ts
__integrations__/models/user_rc_configuration.test.ts
src/models/rc_configuration.ts
src/models/user_rc_configuration.ts

* Add `findAllLastVersionByConfigurationId` for rc_configuration;
* Add `findAllByUserId` for user_rc_configuration.
Those methots are necessary to add the `ListRCConfiguration` function.
Integration test

[#IOCOM-1160] Add findAll for RC

---

package.json
yarn.lock

[#IOPLT-403] Upgrade App insights sdk

---

src/models/rc_configuration_non_versioned_temp.ts

Added a temporary non versioned model with some defaults to get rc configurations as if they are non versioned.
We need to migrate to a non versioned model.

[IOCOM-1362] Added temporary model

---

package.json
yarn.lock

Upgrade io-ts-commons

---

src/mailer/mailup.ts

1. Add `Attachments` fields in Mailup payload (as documented [here](https://help.mailup.com/wiki/spaces/mailupapi/pages/36342655/Transactional+Emails+using+APIs#TransactionalEmailsusingAPIs-SendMessage))
We want to send transactional e-mails with attachments.

[IOCOM-1945] Add support for attachments in Mailup transport

---

src/entities/validation_token.ts
src/utils/azure_storage.ts
src/utils/data_tables.ts
src/utils/unique_email_enforcement/storage.ts

- Create `TableEntityAzureDataTables` to handle the new camel case `partitionKey` and `rowKey` of `@azure/data-tables` library.
- Create `ValidationTokenEntityAzureDataTables` to use the new `TableEntityAzureDataTables`
The library `@azure/data-tables` returns an Entity with the partition and row keys in camel case, opposed to the pascal case used by the deprecated library `azure-storage`.
Since the functions  such `io-functions-public` as are being updated with the newest library, the validation of the entities will fail on the mismatched keys.
This PR will address this issue by exposing a new `TableEntityAzureDataTables` and `ValidationTokenEntityAzureDataTables` which can be used to validate an Entity retrieved with `@azure/data-tables`.

[#IOPID-2428] Update `ValidationTokenEntity` to support `@azure/data-tables`

---

openapi/definitions.yaml

OpenAPI: deprecate token_name field
`token_name` field is no longer used

[IOPAE-2091] OpenAPI: deprecate token_name field
